// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaCnN2Xa2DjHR9Xzw8qkeI1X-mNf2zhY',
    appId: '1:10227776420:web:a77483019f8501938d5f31',
    messagingSenderId: '10227776420',
    projectId: 'distributionwog',
    authDomain: 'distributionwog.firebaseapp.com',
    storageBucket: 'distributionwog.appspot.com',
    measurementId: 'G-KX57039S4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApusqBmgYpMD6fMIGHSLpzEtqXc-2fHug',
    appId: '1:10227776420:android:e0d1d58da3fba4f78d5f31',
    messagingSenderId: '10227776420',
    projectId: 'distributionwog',
    storageBucket: 'distributionwog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpIFdqe9vN0COIkwf1inGglsOU6VZCSwQ',
    appId: '1:10227776420:ios:fc4886535754ae2d8d5f31',
    messagingSenderId: '10227776420',
    projectId: 'distributionwog',
    storageBucket: 'distributionwog.appspot.com',
    iosBundleId: 'com.example.flutterWogDistribution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpIFdqe9vN0COIkwf1inGglsOU6VZCSwQ',
    appId: '1:10227776420:ios:fc4886535754ae2d8d5f31',
    messagingSenderId: '10227776420',
    projectId: 'distributionwog',
    storageBucket: 'distributionwog.appspot.com',
    iosBundleId: 'com.example.flutterWogDistribution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPaCnN2Xa2DjHR9Xzw8qkeI1X-mNf2zhY',
    appId: '1:10227776420:web:8f7723e97a7cbd1b8d5f31',
    messagingSenderId: '10227776420',
    projectId: 'distributionwog',
    authDomain: 'distributionwog.firebaseapp.com',
    storageBucket: 'distributionwog.appspot.com',
    measurementId: 'G-XLCX3NN87H',
  );
}
