name: Build & upload to Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # Required for iOS builds

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Set up Google Services and Firebase Options
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FIREBASE_OPTION: ${{ secrets.FIREBASE_OPTION }}
          GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
          echo "$FIREBASE_OPTION" > lib/firebase_options.dart
          echo "$GOOGLE_SERVICE_INFO_PLIST" > ios/Runner/GoogleService-Info.plist

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      # Android Build
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      # iOS Build
      - run: flutter build ipa --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa

      # Upload Android APK to Firebase
      - name: Upload Android APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APPID }}
          token: ${{ secrets.TOKEN }}
          groups: pre-testers
          file: build/app/outputs/apk/release/app-release.apk

      # Upload iOS IPA to Firebase
      - name: Upload iOS IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.IOSID }}
          token: ${{ secrets.TOKEN }}
          groups: pre-testers
          file: build/ios/ipa/*.ipa
